### ISSUE TITLE
New routine 'openhandle' not mentioned in README synopsis

### ISSUE THREAD

**Issue by tbrowder** [lizmat/Scalar-Util#1]

**Comment by lizmat** [comment]
https://modules.raku.org/dist/Scalar::Util:cpan:ELIZABETH is still showing 0.0.6, could that be it?

**Comment by tbrowder** [comment]
No, I don't think so. I see 0.0.7 on everything and I refreshed the page and still see it. And 'openhandle' shows in the list of exported subs and has a description. Also it no longer shows in the routines not ported at the bottom.

**Comment by lizmat** [comment]
Ah, duh  :-)  0.0.8 on its way to CPAN now
